version: 2.1

# orbs:
#   node: circleci/node@2.0.2

references:
  restore_installed_cache: &restore_installed_cache
    restore_cache:
      keys:
        - yarn-{{ checksum "yarn.lock" }}
        - yarn-

  save_installed_cache: &save_installed_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

commands:
  create_service_account_json:
    parameters:
      where:
        type: string
    steps:
      - run:
          name: Create ServiceAccount.json on project root
          command: |
            echo $SERVICE_ACCOUNT | base64 --decode > \
            ${HOME}/<< parameters.where >>/serviceAccount.json
      - run:
          name: Verify ServiceAccount.json creation
          command: cat ${HOME}/<< parameters.where >>/serviceAccount.json

  install_package:
    steps:
      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile --cache-folder ~.cache/yarn



jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/cio
    steps:
      # - run:
      #     name: Decode base64 of Service Account
      #     command: |
      #       export GOOGLE_APPLICATION_CREDENTIALS=$(echo -n $GOOGLE_APPLICATION_CREDENTIALS | base64 --decode)
      #       echo $GOOGLE_APPLICATION_CREDENTIALS

      - checkout
      - create_service_account_json:
          where: cio
      # - run:
      #     name: Create ServiceAccount.json
      #     command: echo $SERVICE_ACCOUNT | base64 --decode > ${HOME}/cio/serviceAccount.json

      # - run:
      #     name: Test if succuess to create ServiceAccount.json
      #     command: cat ${HOME}/cio/serviceAccount.json


      # - node/install:
      #     install-yarn: true
      #     node-version: 12.10.0

      # - run:
      #     name: Show Node Version
      #     command: node --version
      - *restore_installed_cache
      # - run:
      #     name: Show Yarn Version
      #     command: yarn --version
      - install_package
      # - run:
      #     name: Install Packages
      #     command: yarn install --frozen-lockfile --cache-folder ~.cache/yarn
      - *save_installed_cache
      # - save_cache:
      #     name: Save Yarn Package Cache
      #     key: yarn-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      # - run:
      #     name: Cypress on CIO
      #     command: yarn ci:cy:cio
      # - run:
      #     name: Cypress on Storybook
      #     command: yarn ci:cy:storybook
      # - run:
      #     name: Build CIO
      #     command: yarn build:cio
      # - run:
      #     name: Build Storybook
      #     command: yarn build:storybook
      # - run:
      #     name: Deploy CIO to Firebase
      #     command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --only hosting:cio
      # - run:
      #     name: Deploy Storybook to Firebase
      #     command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --only hosting:storybook
workflows:
  version: 2
  workflow_name:
    jobs:
      - build